--liquibase formatted sql
--changeset Moses:3

use recap;

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('version.number','4',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('scsb.app.service.logout','http://52.203.96.232:9091',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('scsb.app.logout.redirect.uri','http://52.203.96.232:9091',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('cas.default.service.login','http://52.203.96.232:8081/cas/login',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('cas.default.service.logout','http://52.203.96.232:8081/cas/logout',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('cas.default.url.prefix','http://52.203.96.232:8081/cas/',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('scsb.app.service.home','http://52.203.96.232:9091',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('scsb.solr.doc.url','http://172.17.0.1:9090/',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('scsb.etl.url','http://172.17.0.1:9094/',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('scsb.circ.url','http://172.17.0.1:9095/',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('scsb.batch.schedule.url','http://172.17.0.1:9096/',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('scsb.gateway.url','http://172.17.0.1:9093/',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('scsb.auth.url','http://172.17.0.1:9092/',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('solr.server.protocol','http://',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('solr.url','172.17.0.1:8983/solr',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('solr.parent.core','recap',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('spring.datasource.url','jdbc:mysql://172.17.0.1:3306/recap?autoReconnect=true&serverTimezone=America/New_York&useSSL=false',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('spring.datasource.driver-class-name','com.mysql.cj.jdbc.Driver',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('spring.datasource.username','recap',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('spring.datasource.password','recap',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('spring.jpa.properties.hibernate.dialect','org.hibernate.dialect.MySQL8Dialect',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('batch.jdbc.url','jdbc:mysql://172.17.0.1:3306/recapbatch?autoReconnect=true&useSSL=false&serverTimezone=America/New_York',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('batch.jdbc.driver','com.mysql.cj.jdbc.Driver',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('batch.jdbc.user','recap',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('batch.jdbc.password','recap',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('activemq.broker.url','tcp://172.17.0.1:61616?jms.objectMessageSerializationDefered=true&wireFormat.maxInactivityDuration=0&wireFormat.maxInactivityDurationInitalDelay=1200000',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('activemq.jmx.service.url','service:jmx:rmi:///jndi/rmi://172.17.0.1:1099/jmxrmi',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('activemq.web.console.url','http://52.203.96.232:8161',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('activemq.credentials','admin:admin',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('activemq.jolokia.api.url','/api/jolokia/read/org.apache.activemq:type=Broker,brokerName=localhost,destinationType=Queue,destinationName=',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('activemq.jolokia.api.queue.size.attribute','/QueueSize',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.smtp.server.username','AKIAITRJXNQ3R6GF4SBQ',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.smtp.server.password.file','/recap-vol/keys/email_pswd',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.smtp.server.address.from','no-reply-phase4-Test@recaplib.org',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.smtp.server','email-smtp.us-east-1.amazonaws.com',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.request.recall.subject','Recall request processed in SCSB',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.status.reconciliation.cc','srini.induri@htcindia.com',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.deleted.records.to','srini.induri@htcindia.com',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.scsb.batch.job.subject','Batch Job',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.scsb.batch.job.to','srini.induri@htcindia.com',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.scsb.updateCgd.subject','Change in Item CGD in ReCAP',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.scsb.updateCgd.to','srini.induri@htcindia.com',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.scsb.updateCgd.cc','recap.collections@library.columbia.edu,recap.accession@library.columbia.edu,kr2@princeton.edu, mzelesky@princeton.edu, wange@princeton.edu,recapreports@nypl.org',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.submit.collection.subject','Submit collection completed',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('submit.collection.partition.size','5000',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('submit.collection.owninginstbibidlist.partition.size','5000',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.submit.collection.subject.for.empty.directory','No files to process for submit collection',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.status.reconciliation.to','scsb-notifications@htcindia.com',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('status.reconciliation.batch.size','100',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('status.reconciliation.day.limit','7',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('status.reconciliation.las.barcode.limit','100',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('status.reconciliation','devops-recap.htcinc.com:2222/share/recap/status-reconciliation/p4tst',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('request.initial.load.filepath','/recap-vol/scsb-circ/request-initial-load',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.request.initial.load.subject','Initial Load of Requests',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ongoing.accession.input.limit','10',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ongoing.accession.collection.report.directory','/recap-vol/scsb-solr-client/reports/collection/ongoinAccession',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('request.initial.accession','devops-recap.htcinc.com:2222/share/recap/request-initial-data/p4tst',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('request.initial.accession.error.file','devops-recap.htcinc.com:2222/share/recap/request-initial-data/p4tst/request-data-invalid-file',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('purge.email.address.edd.request.day.limit','60',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('purge.email.address.physical.request.day.limit','90',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('purge.exception.request.day.limit','365',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('purge.accession.request.day.limit','365',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('submit.collection.input.limit','20',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('scsb.collection.report.directory','/recap-vol/scsb-solr-client/reports/collection',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('submit.collection.report.directory','/recap-vol/scsb-solr-client/reports/collection/submitCollection',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('nonholdingid.institution','NYPL',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('etl.data.load.directory','/recap-vol/scsb-etl/etl-dataload/pending',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('etl.report.directory','/recap-vol/scsb-etl/etl-reports',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('etl.data.dump.directory','/recap-vol/scsb-etl/data-dump',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('etl.data.dump.report.directory','/recap-vol/data-dump/reports',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('etl.data.dump.ftp.staging.directory','/recap-vol/scsb-etl/data-dump/ftp',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('etl.data.dump.fetchtype.full','10',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('etl.data.dump.records.per.file','10000',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('etl.data.dump.incremental.date.limit','5',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('etl.data.dump.deleted.type.onlyorphan.institution','PUL,CUL',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('etl.data.dump.incremental.type.nonfulltree.institution','NYPL',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('etl.data.dump.status.file.name','/recap-vol/scsb-etl/data-dump/dataExportStatus.txt',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.etl.data.dump..subject','[Success] Data dump exported.',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.etl.data.dump.nodata.subject','[No data] Data dump export.',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('daily.reconciliation.file','/recap-vol/scsb/scsb-circ/DailyReconciliation',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.daily.reconciliation','devops-recap.htcinc.com:2222/share/recap/daily-reconciliation/p4tst',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.daily.reconciliation.processed','devops-recap.htcinc.com:2222/share/recap/daily-reconciliation/processed/p4tst',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.daily.reconciliation.to','srini.induri@htcindia.com',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('daily.reconciliation.local.work.dir','/data/scsb-circ/daily-reconciliation',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('etl.error.output.file.path','/recap-vol/scsb-etl',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('include.matching.algorithm.in.sequence.job','1',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('include.submit.collection.in.sequence.job','1',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('include.data.export.in.sequence.job','1',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('long.running.jobs.poller.time.in.minutes','60',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('bulk.request.concurrent.consumer.count','1',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('bulk.request.item.count.limit','1000',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.bulk.request.to','srini.induri@htcindia.com',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('request.pending.limit','10',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('superadmin.permission.institution','HTC',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('scsb.api.key','361d1afc9a5e2760455f55ab6e360f75,c8a129203937b44a0b59972176bbfe52,c4f03659a45e2850163f4d3454d625fd,2e999034c11f985a10bb43984e718590,135a78305d04af6bca6c9717525fb7ab,12c94a3e0711a891aee1f039656f8ab3,36b8fd14e8d87c3654bc13fb478dbb6a,6759de49d535f7a179ea9f1d3288d6b3',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('scsb.swagger.api.key','recap',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('scsb.encryption.secretkey','secretrecapemail',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.smtp.server.data.dump.username','AKIAITRJXNQ3R6GF4SBQ',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.smtp.server.data.dump.password.file','/recap-vol/keys/email_pswd',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.data.dump.from','no-reply-Phase4-test-data-dump@recaplib.org',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.data.dump.subject','datadumpemailsubject',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.data.dump.nodata.subject','no-dump-email-subject',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('solr.exception.report.directory','/recap-vol/scsb-solr-client/reports/solr-reports',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('matching.report.directory','/recap-vol/scsb-solr-client/reports/matchingAlgorithmReports',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.server.privateKey','/recap-vol/keys/ftprecap_rsa',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.server.knownHost','/recap-vol/keys/known_hosts',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.server.userName','recapftp',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.server','devops-recap.htcinc.com',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.server.port','2222',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.server.password','recap',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.etl.reports.dir','devops-recap.htcinc.com:2222/share/etl-reports/p4tst',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.data.dump.dir','devops-recap.htcinc.com:2222/share/recap/data-dump/p4tst',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.data.dump.report.dir','devops-recap.htcinc.com:2222/share/recap/data-dump-reports/p4tst',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.matchingAlgorithm.reports.dir','devops-recap.htcinc.com:2222/share/recap/matching-reports/p4tst',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.submit.collection.report.dir','devops-recap.htcinc.com:2222/share/recap/reports/collection/submitCollection/p4tst',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.ongoing.accession.collection.report.dir','devops-recap.htcinc.com:2222/share/recap/reports/collection/ongoinAccession/p4tst',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.solr.reports.dir','devops-recap.htcinc.com:2222/share/recap/solr-reports/p4tst',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('spring.rabbitmq.host', '172.17.0.1', 'Y', '2020-10-07 00:00:00', '2020-10-07 00:00:00', 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('spring.rabbitmq.username', 'rabbit', 'Y', '2020-10-07 00:00:00', '2020-10-07 00:00:00', 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('spring.rabbitmq.password', 'rabbit', 'Y', '2020-10-07 00:00:00', '2020-10-07 00:00:00', 'Script', 'Script');



# PUL Specific 

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('protocol','SIP2',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.server.port','7031',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('auth.service.login','https://fed.princeton.edu/cas/login',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('auth.service.logout','https://fed.princeton.edu/cas/logout?service',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('auth.service.prefix','https://fed.princeton.edu/cas',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('auth.type','cas',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.server','libserv86.princeton.edu',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.bibdata.api.endpoint','https://bibdata.princeton.edu/barcode/{barcode}/scsb',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.bibdata.api.parameter','',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.server.operator.user.id','htcsc1',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.server.operator.password','MdlW@419r&',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.server.operator.location','htcsc',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.recall.request.to','srini.induri@htcindia.com',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.accession.reconciliation.to','srini.induri@htcindia.com',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.accession.reconciliation.cc','srini.induri@htcindia.com',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.submit.collection.to','srini.induri@htcindia.com',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.submit.collection.cc','srini.induri@htcindia.com',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('request.initial.load.filepath','/recap-vol/scsb-circ/request-initial-load/pul',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('request.initial.load.workdir','/recap-vol/scsb-circ/request-initial-load/work/pul',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.request.initial.accession.dir','devops-recap.htcinc.com:2222/share/recap/request-initial-data/p4tst/pul',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.request.initial.accession.error.file','devops-recap.htcinc.com:2222/share/recap/request-initial-data/p4tst/pul/request-data-invalid-file',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.request.initial.load.to','srini.induri@htcindia.com',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('accession.reconciliation.workdir','/data/scsb-circ/accession-reconciliation/pul',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.accession.reconciliation.dir','devops-recap.htcinc.com:2222/share/recap/accession-reconciliation/p4tst/pul',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.accession.reconciliation.processed.dir','devops-recap.htcinc.com:2222/share/recap/accession-reconciliation/processed/p4tst/pul',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.accession.reports.to','srini.induri@htcindia.com',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('submit.collection.fileprocess.workdir','/recap-vol/scsb-circ/submitcollection/pul',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.submit.collection.nofiles.to','srini.induri@htcindia.com',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.request.refile.to','kr2@princeton.edu, mzelesky@princeton.edu, wange@princeton.edu,scsb-notifications@htcindia.com',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.request.recall.cc','scsb-notifications@htcindia.com',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.edd.patron.id','198572131',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.cul.edd.patron.id','198572132',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.nypl.edd.patron.id','198572133',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.cul.cross.partner.patron.id','198572368',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.nypl.cross.partner.patron.id','198572369',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('etl.initial.data.loaded.date','2017-05-21',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.data.dump.to','srini.induri@htcindia.com',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.data.dump.cc','srini.induri@htcindia.com',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.matching.reports.to','srini.induri@htcindia.com',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.admin.role.to','Recapproblems@princeton.edu',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.technical.support.to','mzelesky@princeton.edu',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.submit.collection.report.dir','devops-recap.htcinc.com:2222/share/recap/reports/collection/submitCollection/p4tst/pul',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.submit.collection.cgdprotected.dir','/share/recap/submitcollection/p4tst/pul/cgd_protection',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.submit.collection.cgdnotprotected.dir','/share/recap/submitcollection/p4tst/pul/no_cgd_protection',NULL,'PUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

## New Script From Rajesh
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.create.bib.api.enabled', 'true', 'PUL', 'Y', '2020-09-15 00:00:00', '2020-09-15 00:00:00', 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.topic.retrieval.request', 'scsbactivemq:topic:PUL.RequestT', 'PUL', 'Y', CURDATE(), CURDATE(), 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.topic.edd.request', 'scsbactivemq:topic:PUL.EDDT', 'PUL', 'Y', CURDATE(), CURDATE(), 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.topic.recall.request', 'scsbactivemq:topic:PUL.RecallT', 'PUL', 'Y', CURDATE(), CURDATE(), 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.topic.borrowdirect.request', 'scsbactivemq:topic:PUL.BorrowDirectT', 'PUL', 'Y', CURDATE(), CURDATE(), 'Script', 'Script');

INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.use.refile.for.checkin', 'false', 'PUL', 'Y', '2020-09-15 00:00:00', '2020-09-15 00:00:00', 'Script', 'Script');

## New Script From Hari
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `description`, `institution_code`, `ims_location_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.refile.endpoint.protocol', 'SIP2', '', 'PUL', '', 'Y', now(), now(), 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `description`, `institution_code`, `ims_location_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('bibdata.format', 'MARC', '', 'PUL', '', 'Y', now(), now(), 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `description`, `institution_code`, `ims_location_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.bibdata.api.auth', 'NoAuth', '', 'PUL', '', 'Y', now(), now(), 'Script', 'Script');



# CUL Specific

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('protocol','SIP2',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.server.port','7031',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('auth.service.login','https://cas.columbia.edu/cas/login',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('auth.service.logout','https://cas.columbia.edu/cas/logout?service',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('auth.service.prefix','https://cas.columbia.edu/cas',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('auth.type','cas',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.server','voyagertestapp01.cc.columbia.edu',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.bibdata.api.endpoint','https://bibdata.library.columbia.edu/barcode/{barcode}',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.bibdata.api.parameter','',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.server.operator.user.id','recapd2d',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.server.operator.password','42-culRD',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.server.operator.location','CIRCrecap',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.edd.patron.id','RECAPCUL01',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.pul.edd.patron.id','RECAPPUL02',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.nypl.edd.patron.id','RECAPNYPL2',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.pul.cross.partner.patron.id','RECAPPUL01',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.nypl.cross.partner.patron.id','RECAPNYPL1',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('request.initial.load.filepath','/recap-vol/scsb-circ/request-initial-load/cul',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('request.initial.load.workdir','/recap-vol/scsb-circ/request-initial-load/work/cul',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.request.initial.accession.dir','devops-recap.htcinc.com:2222/share/recap/request-initial-data/p4tst/cul',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.request.initial.accession.error.file','devops-recap.htcinc.com:2222/share/recap/request-initial-data/p4tst/cul/request-data-invalid-file',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.request.initial.load.to','srini.induri@htcindia.com',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('accession.reconciliation.workdir','/data/scsb-circ/accession-reconciliation/cul',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.accession.reconciliation.dir','devops-recap.htcinc.com:2222/share/recap/accession-reconciliation/p4tst/cul',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.accession.reconciliation.processed.dir','devops-recap.htcinc.com:2222/share/recap/accession-reconciliation/processed/p4tst/cul',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.accession.reports.to','srini.induri@htcindia.com',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('submit.collection.fileprocess.workdir','/recap-vol/scsb-circ/submitcollection/cul',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.submit.collection.nofiles.to','srini.induri@htcindia.com',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.submit.collection.report.dir','devops-recap.htcinc.com:2222/share/recap/reports/collection/submitCollection/p4tst/cul',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.submit.collection.cgdprotected.dir','/share/recap/submitcollection/p4tst/cul/cgd_protection',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.submit.collection.cgdnotprotected.dir','/share/recap/submitcollection/p4tst/cul/no_cgd_protection',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.recall.request.to','srini.induri@htcindia.com',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.accession.reconciliation.to','srini.induri@htcindia.com',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.accession.reconciliation.cc','srini.induri@htcindia.com',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.request.refile.to','srini.induri@htcindia.com',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.request.recall.cc','recap.circulation@library.columbia.edu',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.submit.collection.to','srini.induri@htcindia.com',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.submit.collection.cc','srini.induri@htcindia.com',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('etl.initial.data.loaded.date','2017-05-21',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.data.dump.to','srini.induri@htcindia.com',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.data.dump.cc','srini.induri@htcindia.com',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.matching.reports.to','srini.induri@htcindia.com',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.technical.support.to','recap.admin@library.columbia.edu',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.admin.role.to','',NULL,'CUL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

## New Script From Rajesh
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.create.bib.api.enabled', 'true', 'CUL', 'Y', '2020-09-15 00:00:00', '2020-09-15 00:00:00', 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.topic.retrieval.request', 'scsbactivemq:topic:CUL.RequestT', 'CUL', 'Y', CURDATE(), CURDATE(), 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.topic.edd.request', 'scsbactivemq:topic:CUL.EDDT', 'CUL', 'Y', CURDATE(), CURDATE(), 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.topic.recall.request', 'scsbactivemq:topic:CUL.RecallT', 'CUL', 'Y', CURDATE(), CURDATE(), 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.topic.borrowdirect.request', 'scsbactivemq:topic:CUL.BorrowDirectT', 'CUL', 'Y', CURDATE(), CURDATE(), 'Script', 'Script');

INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.use.refile.for.checkin', 'false', 'CUL', 'Y', '2020-09-15 00:00:00', '2020-09-15 00:00:00', 'Script', 'Script');

## New Script From Hari

INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `description`, `institution_code`, `ims_location_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('bibdata.format', 'MARC', '', 'CUL', '', 'Y', now(), now(), 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `description`, `institution_code`, `ims_location_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.bibdata.api.auth', 'NoAuth', '', 'CUL', '', 'Y', now(), now(), 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `description`, `institution_code`, `ims_location_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.refile.endpoint.protocol', 'SIP2', '', 'CUL', '', 'Y', now(), now(), 'Script', 'Script'); 



# NYPL Specific 
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('protocol','REST',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.server.port','0',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('oauth2.client.clientid','htc_scsb',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('oauth2.client.clientSecret','m0Fg7xbm3ZPq5djD3gBHTu3mQYrBpf6U',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('oauth2.client.registered-redirect-uri','http://52.203.96.232:9091/login',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('oauth2.client.pre-established-redirect-uri','http://52.203.96.232:9091/login',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('auth.type','OAuth2',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('oauth2.client.scope','openid offline_access login:staff role:client read:item read:patron write:hold_request write:checkin_request write:checkout_request write:recall_request write:refile_request',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('oauth2.resource.jwt.key-value','-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA44ilHg/PxcJYsISHMRyo\nxsmez178qZpkJVXg7rOMVTLZuf05an7Pl+lX4nw/rqcvGQDXyrimciLgLkWu00xh\nm6h6klTeJSNq2DgseF8OMw2olfuBKq1NBQ/vC8U0l5NJu34oSN4/iipgpovqAHHB\nGV4zDt0EWSXE5xpnBWi+w1NMAX/muB2QRfRxkkhueDkAmwKvz5MXJPay7FB/WRjf\n+7r2EN78x5iQKyCw0tpEZ5hpBX831SEnVULCnpFOcJWMPLdg0Ff6tBmgDxKQBVFI\nQ9RrzMLTqxKnVVn2+hVpk4F/8tMsGCdd4s/AJqEQBy5lsq7ji1B63XYqi5fc1SnJ\nEQIDAQAB\n-----END PUBLIC KEY-----\n',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('oauth.token.api.url','https://isso.nypl.org/oauth/token',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.server.operator.user.id','htc_scsb',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.server.operator.password','m0Fg7xbm3ZPq5djD3gBHTu3mQYrBpf6U',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('oauth.resource.jwt.key-value','-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtmIMVmUnbwr/65MYmLGJ\nm4aDXd0AmYI/Ww2yRye4LR2fmB6qrgdyiidmR1qV86kS287MzfYBYoTEYYjDQI0f\nVLlH0es8ubifn0cM4hnwDnNJds3JYohen2OM+08qEsOCSIlsTJ2YDHNmUAMIiIRs\nay1efUPq98iAUAZkDr/M6ytwh+Sa9xmaeXVjJxUu0E8sCrqFuuZ7qm8A0ljlncLv\nUCbulaUg9lKM8SPfaWu2O4Xr1YupmyIlYkWDzbqIZbpu8cv0nnNOonEOVckjwhMz\nM7lSsQ05AXR0VAsZzafkpcC/yFp2Dfa2ZsKJNv/TDmYGDQ6wHgtU51ZEVq48jBz9\ncQIDAQAB\n-----END PUBLIC KEY-----\n',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.rest.data.api','https://qa-platform.nypl.org/api/v0.1',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.bibdata.api.endpoint','https://qa-platform.nypl.org/api',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.bibdata.api.parameter','/v0.1/recap/nypl-bibs?barcode={barcode}&customercode={customercode}',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.server.operator.location','',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.edd.patron.id','23333090796036',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.pul.edd.patron.id','23333090796010',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.cul.edd.patron.id','23333090796028',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.pul.cross.partner.patron.id','70620957062095',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.cul.cross.partner.patron.id','70620917062091',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ils.rest.polling.max.timeout','60',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.submit.collection.report.dir','devops-recap.htcinc.com:2222/share/recap/reports/collection/submitCollection/p4tst/nypl',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.submit.collection.cgdprotected.dir','/share/recap/submitcollection/p4tst/nypl/cgd_protection',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.submit.collection.cgdnotprotected.dir','/share/recap/submitcollection/p4tst/nypl/no_cgd_protection',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.recall.request.to','srini.induri@htcindia.com',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.accession.reconciliation.to','srini.induri@htcindia.com',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.accession.reconciliation.cc','srini.induri@htcindia.com',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.request.refile.to','scsb-notifications@htcindia.com,recapreports@nypl.org',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.request.recall.cc','Recalls@nypl.org,recapreports@nypl.org',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.submit.collection.to','srini.induri@htcindia.com',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.submit.collection.cc','srini.induri@htcindia.com',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('request.initial.load.filepath','/recap-vol/scsb-circ/request-initial-load/nypl',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('request.initial.load.workdir','/recap-vol/scsb-circ/request-initial-load/work/nypl',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.request.initial.accession.dir','devops-recap.htcinc.com:2222/share/recap/request-initial-data/p4tst/nypl',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.request.initial.accession.error.file','devops-recap.htcinc.com:2222/share/recap/request-initial-data/p4tst/nypl/request-data-invalid-file',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.request.initial.load.to','srini.induri@htcindia.com',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('accession.reconciliation.workdir','/data/scsb-circ/accession-reconciliation/nypl',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.accession.reconciliation.dir','devops-recap.htcinc.com:2222/share/recap/accession-reconciliation/p4tst/nypl',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('ftp.accession.reconciliation.processed.dir','devops-recap.htcinc.com:2222/share/recap/accession-reconciliation/processed/p4tst/nypl',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.accession.reports.to','srini.induri@htcindia.com',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('etl.initial.data.loaded.date','2017-05-21',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.data.dump.to','srini.induri@htcindia.com',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.data.dump.cc','srini.induri@htcindia.com',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.matching.reports.to','srini.induri@htcindia.com',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.technical.support.to','ReCAPinterface@nypl.org',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.admin.role.to','',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('submit.collection.fileprocess.workdir','/recap-vol/scsb-circ/submitcollection/nypl',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('email.submit.collection.nofiles.to','srini.induri@htcindia.com',NULL,'NYPL',NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

## New Script From Rajesh

INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.create.bib.api.enabled', 'false', 'NYPL', 'Y', '2020-09-15 00:00:00', '2020-09-15 00:00:00', 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.topic.retrieval.request', 'scsbactivemq:topic:NYPL.RequestT', 'NYPL', 'Y', CURDATE(), CURDATE(), 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.topic.edd.request', 'scsbactivemq:topic:NYPL.EDDT', 'NYPL', 'Y', CURDATE(), CURDATE(), 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.topic.recall.request', 'scsbactivemq:topic:NYPL.RecallT', 'NYPL', 'Y', CURDATE(), CURDATE(), 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.topic.borrowdirect.request', 'scsbactivemq:topic:NYPL.BorrowDirectT', 'NYPL', 'Y', CURDATE(), CURDATE(), 'Script', 'Script');

INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `institution_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.use.refile.for.checkin', 'true', 'NYPL', 'Y', '2020-09-15 00:00:00', '2020-09-15 00:00:00', 'Script', 'Script');


## New Script From Hari

INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `description`, `institution_code`, `ims_location_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('bibdata.format', 'SCSB', '', 'NYPL', '', 'Y', now(), now(), 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `description`, `institution_code`, `ims_location_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.bibdata.api.auth', 'OAuth', '', 'NYPL', '', 'Y', now(), now(), 'Script', 'Script');
INSERT INTO `scsb_properties_t` (`p_key`, `p_value`, `description`, `institution_code`, `ims_location_code`, `active`, `created_date`, `updated_date`, `created_by`, `updated_by`) VALUES ('ils.refile.endpoint.protocol', 'REST', '', 'NYPL', '', 'Y', now(), now(), 'Script', 'Script');



# Location Specific

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('recap.las.use.queue','true',NULL,NULL,'RECAP_LAS','Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('recap-las.server.response.timeout.milliseconds','30000',NULL,NULL,'RECAP_LAS','Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('recap-las.item.status.endpoint','http://recapgfa-dev.princeton.edu:9092/lasapi/rest/lasapiSvc/itemStatus',NULL,NULL,'RECAP_LAS','Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('recap-las.item.retrieval.order.endpoint','http://recapgfa-dev.princeton.edu:9092/lasapi/rest/lasapiSvc/retrieveItem',NULL,NULL,'RECAP_LAS','Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('recap-las.item.edd.retrieval.order.endpoint','http://recapgfa-dev.princeton.edu:9092/lasapi/rest/lasapiSvc/retrieveEDD',NULL,NULL,'RECAP_LAS','Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('recap-las.permanent.withdrawl.direct.endpoint','http://recapgfa-dev.princeton.edu:9092/lasapi/rest/lasapiSvc/permanentlyRetrieveItem',NULL,NULL,'RECAP_LAS','Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('recap-las.item.permanent.withdrawl.indirect','http://recapgfa-dev.princeton.edu:9092/lasapi/rest/lasapiSvc/permanentlyRetrieveItemIndirect',NULL,NULL,'RECAP_LAS','Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('recap-las.email.recap.assist.email.to','srini.induri@htcindia.com',NULL,NULL,'RECAP_LAS','Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('recap-las.email.request.cancel.email.recap.to','srini.induri@htcindia.com',NULL,NULL,'RECAP_LAS','Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('recap-las.email.request.refile.to','srini.induri@htcindia.com',NULL,NULL,'RECAP_LAS','Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('recap-las.email.request.recall.cc','srini.induri@htcindia.com',NULL,NULL,'RECAP_LAS','Y',CURDATE(),CURDATE(),'Script','Script');

#Mock Server

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('htc.auth.service.login','http://52.203.96.232:8081/cas/login',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('htc.auth.service.logout','http://52.203.96.232:8081/cas/logout?service',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('htc.auth.service.prefix','http://52.203.96.232:8081/cas',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('htc.auth.type','cas',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('monitoring.grafana.port','5001',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('logging.kibana.port','5501',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('logging.ui.url','http://localhost:${kibana.port}/app/kibana#/discover/57f427e0-c4cd-11ea-b053-1f1f5849d048',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('monitoring.ui.url','http://localhost:${grafana.port}/d/spring_boot_21/scsb-applications-general-metrics?orgId=1',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('logging.embed.ui.url','http://localhost:${kibana.port}/app/kibana#/discover/57f427e0-c4cd-11ea-b053-1f1f5849d048',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('monitoring.embed.ui.url','http://localhost:${grafana.port}/d/spring_boot_21/scsb-applications-general-metrics?orgId=1',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('monitoring.embed.docker.url','http://localhost:${grafana.port}/d/UD35UEgGz/docker-host-and-container-overview?orgId=1&refresh=5m',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('monitoring.embed.aws.url','http://localhost:${grafana.port}/d/hb7fSE0Zz/aws-test-server-metrics?orgId=1',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('spring.sleuth.sampler.probability','1',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.email.username','AKIAITRJXNQ3R6GF4SBQ',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.email.password.file','/recap-vol/keys/mail_pswd',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.email.from','srini.induri@htcindia.com',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.email.smtpServer','email-smtp.us-east-1.amazonaws.com',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.ils.pul.operator.user.id','recap',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.ils.pul.operator.password','recap',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.ils.pul.operator.location','location',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.ils.cul.operator.user.id','recap',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.ils.cul.operator.password','recap',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.ils.cul.operator.location','CIRCrecap',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.ils.nypl.data.api','http://172.17.0.12:8090/rest',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.ils.nypl.sip.server.url','172.17.0.13',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.ils.nypl.sip.server.port','8012',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.ils.pul.port','8012',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.ils.pul','172.17.0.13',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');
INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.ils.cul','172.17.0.13',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');

INSERT INTO `scsb_properties_t` (`p_key`,`p_value`,`description`,`institution_code`,`ims_location_code`,`active`,`created_date`,`updated_date`,`created_by`,`updated_by`) VALUES ('mock.server.recap-las.item.status.endpoint','http://172.17.0.1:8080/lasapi/rest/lasapiSvc/itemStatus',NULL,NULL,NULL,'Y',CURDATE(),CURDATE(),'Script','Script');






