--liquibase formatted sql
--changeset Moses:1

use recap;

CREATE TABLE IF NOT EXISTS IMS_LOCATION_T (

IMS_LOCATION_ID INT NOT NULL AUTO_INCREMENT,

IMS_LOCATION_CODE VARCHAR(45) NOT NULL UNIQUE,

IMS_LOCATION_NAME VARCHAR(255) NOT NULL,

DESCRIPTION  VARCHAR(255) ,

ACTIVE CHAR(1)  NOT NULL,

CREATED_BY VARCHAR(255) NOT NULL,

CREATED_DATE TIMESTAMP NOT NULL ,

UPDATED_BY  VARCHAR(255) NOT NULL ,

UPDATED_DATE TIMESTAMP NOT NULL,

PRIMARY KEY ( IMS_LOCATION_ID )

);

CREATE TABLE IF NOT EXISTS SCSB_PROPERTIES_T (

SCSB_PROPERTIES_ID INT NOT NULL AUTO_INCREMENT,

P_KEY VARCHAR (255) NOT NULL ,

P_VALUE VARCHAR(1500) NOT NULL  ,

DESCRIPTION  VARCHAR(255) ,

INSTITUTION_CODE  VARCHAR(50) ,

IMS_LOCATION_CODE VARCHAR(50) ,

ACTIVE CHAR(1)  NOT NULL,

CREATED_DATE TIMESTAMP NOT NULL ,

UPDATED_DATE TIMESTAMP ,

CREATED_BY  VARCHAR(255) NOT NULL,

UPDATED_BY  VARCHAR(255) ,

PRIMARY KEY ( SCSB_PROPERTIES_ID )

);

CREATE TABLE IF NOT EXISTS INSTITUTION_IMS_LOCATION_T (

INSTITUTION_IMS_LOCATION_ID   INT NOT NULL AUTO_INCREMENT,

INSTITUTION_ID  INT  NOT NULL UNIQUE,

IMS_LOCATION_ID INT NOT NULL,

ACTIVE CHAR(1)  NOT NULL,

CREATED_BY VARCHAR(255) NOT NULL,

CREATED_DATE TIMESTAMP NOT NULL ,

UPDATED_BY  VARCHAR(255) NOT NULL ,

UPDATED_DATE TIMESTAMP NOT NULL,

PRIMARY KEY ( INSTITUTION_IMS_LOCATION_ID ),
FOREIGN KEY (INSTITUTION_ID) REFERENCES INSTITUTION_T (INSTITUTION_ID),
FOREIGN KEY (IMS_LOCATION_ID) REFERENCES IMS_LOCATION_T (IMS_LOCATION_ID)

);

CREATE TABLE IF NOT EXISTS GENERIC_PATRON_T (

GENERIC_PATRON_ID   INT NOT NULL AUTO_INCREMENT,

REQUESTING_INST_ID  INT  NOT NULL UNIQUE,

ITEM_OWN_INST_ID INT NOT NULL,

EDD_GENERIC_PATRON VARCHAR(20) ,

RETRIEVAL_GENERIC_PARTRON VARCHAR(20),

CREATED_BY VARCHAR(255) NOT NULL,

CREATED_DATE TIMESTAMP NOT NULL ,

UPDATED_BY  VARCHAR(255) NOT NULL ,

UPDATED_DATE TIMESTAMP NOT NULL,

PRIMARY KEY ( GENERIC_PATRON_ID ),
FOREIGN KEY (REQUESTING_INST_ID) REFERENCES INSTITUTION_T (INSTITUTION_ID),
FOREIGN KEY (ITEM_OWN_INST_ID) REFERENCES INSTITUTION_T (INSTITUTION_ID)

);


--changeset Suresh:2

RENAME TABLE BIBLIOGRAPHIC_HOLDINGS_T TO BIBLIOGRAPHIC_HOLDINGS_HISTORY_T;
RENAME TABLE BIBLIOGRAPHIC_ITEM_T TO BIBLIOGRAPHIC_ITEM_HISTORY_T;
RENAME TABLE ITEM_HOLDINGS_T TO ITEM_HOLDINGS_HISTORY_T;

ALTER TABLE `BIBLIOGRAPHIC_HOLDINGS_HISTORY_T`
DROP FOREIGN KEY `OWNING_INST_ID_OWNING_INST_BIB_ID_FK`,
DROP FOREIGN KEY `OWNING_INST_HOLDINGS_ID_FK`;
ALTER TABLE `BIBLIOGRAPHIC_HOLDINGS_HISTORY_T`
DROP INDEX `OWNING_INST_ID_OWNING_INST_BIB_ID_FK` ,
DROP INDEX `OWNING_INST_HOLDINGS_ID_FK` ;

ALTER TABLE `BIBLIOGRAPHIC_ITEM_HISTORY_T`
DROP FOREIGN KEY `ITEM_INST_ID_OWNING_INST_ITEM_ID_FK`,
DROP FOREIGN KEY `BIB_INST_ID_OWNING_INST_BIB_ID_FK`;
ALTER TABLE `BIBLIOGRAPHIC_ITEM_HISTORY_T`
DROP INDEX `ITEM_INST_ID_OWNING_INST_ITEM_ID_FK` ,
DROP INDEX `BIB_INST_ID_OWNING_INST_BIB_ID_FK` ;

ALTER TABLE `ITEM_HOLDINGS_HISTORY_T`
DROP FOREIGN KEY `OWNING_INST_ITEM_ID_ITEM_INST_ID_FK`,
DROP FOREIGN KEY `HOLDINGS_INST_ID_OWNING_INST_HOLDINGS_ID_FK`;
ALTER TABLE `ITEM_HOLDINGS_HISTORY_T`
DROP INDEX `OWNING_INST_ITEM_ID_ITEM_INST_ID_FK` ,
DROP INDEX `HOLDINGS_INST_ID_OWNING_INST_HOLDINGS_ID_FK` ;


CREATE TABLE IF NOT EXISTS `BIBLIOGRAPHIC_HOLDINGS_T` (
  `BIBLIOGRAPHIC_HOLDINGS_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `BIBLIOGRAPHIC_ID` INT(11) NOT NULL,
  `HOLDINGS_ID` INT(11) NOT NULL,
  PRIMARY KEY (`BIBLIOGRAPHIC_HOLDINGS_ID`),
  UNIQUE KEY `BIBLIOGRAPHIC_HOLDINGS_UK` (`BIBLIOGRAPHIC_ID`,`HOLDINGS_ID`),
  KEY `BIBLIOGRAPHIC_HOLDINGS_ID` (`BIBLIOGRAPHIC_HOLDINGS_ID`),
  KEY `BIBLIOGRAPHIC_ID` (`BIBLIOGRAPHIC_ID`),
  KEY `HOLDINGS_ID` (`HOLDINGS_ID`),
  CONSTRAINT `BIBLIOGRAPHIC_ID_FK` FOREIGN KEY (`BIBLIOGRAPHIC_ID`) REFERENCES `BIBLIOGRAPHIC_t` (`BIBLIOGRAPHIC_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `HOLDINGS_ID_FK` FOREIGN KEY (`HOLDINGS_ID`) REFERENCES `HOLDINGS_t` (`HOLDINGS_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1025 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `ITEM_HOLDINGS_T` (
  `ITEM_HOLDINGS_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `HOLDINGS_ID` INT(11) NOT NULL,
  `ITEM_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ITEM_HOLDINGS_ID`),
  UNIQUE KEY `ITEM_HOLDINGS_UK` (`HOLDINGS_ID`, `ITEM_ID`),
  KEY `ITEM_HOLDINGS_ID` (`ITEM_HOLDINGS_ID`),
  KEY `ITEM_ID` (`ITEM_ID`),
  KEY `HOLDINGS_ID_1` (`HOLDINGS_ID`),
  CONSTRAINT `ITEM_ID_FK` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM_T` (`ITEM_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `HOLDINGS_ID_FK1` FOREIGN KEY (`HOLDINGS_ID`) REFERENCES `HOLDINGS_T` (`HOLDINGS_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1025 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `BIBLIOGRAPHIC_ITEM_T` (
  `BIBLIOGRAPHIC_ITEM_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `BIBLIOGRAPHIC_ID` INT(11) NOT NULL,
  `ITEM_ID` INT(11) NOT NULL,
  PRIMARY KEY (`BIBLIOGRAPHIC_ITEM_ID`),
  UNIQUE KEY `BIBLIOGRAPHIC_ITEM_UK` (`BIBLIOGRAPHIC_ID`,`ITEM_ID`),
  KEY `BIBLIOGRAPHIC_ITEM_ID` (`BIBLIOGRAPHIC_ITEM_ID`),
  KEY `BIBLIOGRAPHIC_ID1` (`BIBLIOGRAPHIC_ID`),
  KEY `ITEM_ID1` (`ITEM_ID`),
  CONSTRAINT `BIBLIOGRAPHIC_ID_FK1` FOREIGN KEY (`BIBLIOGRAPHIC_ID`) REFERENCES `BIBLIOGRAPHIC_T` (`BIBLIOGRAPHIC_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ITEM_ID_FK1` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM_T` (`ITEM_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1025 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
